package com.example.safesteps;
import android.accessibilityservice.AccessibilityService;import android.graphics.*;import android.graphics.drawable.*;import android.os.Handler;import android.view.*;import android.view.accessibility.AccessibilityEvent;import android.widget.*;import java.util.*;
public class GuardAccessibilityService extends AccessibilityService {
 private final Handler h=new Handler();private WindowManager wm;private View overlay;private boolean blocking;private long last;
 public void onServiceConnected(){super.onServiceConnected();wm=(WindowManager)getSystemService(WINDOW_SERVICE);}
 public void onAccessibilityEvent(AccessibilityEvent e){if(e==null||!getSharedPreferences(MainActivity.PREFS,0).getBoolean(MainActivity.ENABLED,false))return;String p=String.valueOf(e.getPackageName());if(getPackageName().equals(p))return;if(forbidden(e,p))block();}
 private boolean forbidden(AccessibilityEvent e,String pkg){String cls=low(e.getClassName()),text=low(e.getText()),desc=low(e.getContentDescription()),all=text+" "+desc;
  if(pkg.equals("com.android.packageinstaller")||pkg.equals("com.google.android.packageinstaller")||pkg.equals("com.android.permissioncontroller")||pkg.equals("com.google.android.permissioncontroller"))return true;
  if(pkg.equals("com.android.settings")){if(accessibility(cls,text))return true;if(admin(cls,all))return true;if(details(cls,all))return true;}
  return (all.contains("התקן")||all.contains("install"))&&(all.contains("safe steps")||all.contains("safesteps")||all.contains("אפליקציה"));}
 private boolean accessibility(String c,String t){return c.contains("accessibility")||c.contains("installedaccessibility")||(c.contains("subsettings")&&(t.contains("נגישות")||t.contains("accessibility")));}
 private boolean admin(String c,String a){return (c.contains("deviceadmin")||c.contains("device_admin"))||((a.contains("מנהלי המכשיר")||a.contains("מנהלי מכשירים")||a.contains("device administrators")||a.contains("device admin"))&&(c.contains("settings")||c.contains("subsettings")));}
 private boolean details(String c,String a){boolean d=c.contains("appdetails")||c.contains("installedappdetails")||c.contains("manageapplications")||c.contains("applicationdetails");return d&&(a.contains("safe steps")||a.contains("safesteps"));}
 private String low(CharSequence s){return String.valueOf(s==null?"":s).toLowerCase(Locale.ROOT);}
 private void block(){long n=System.currentTimeMillis();if(blocking||n-last<100){return;}last=n;blocking=true;show();h.postDelayed(()->performGlobalAction(GLOBAL_ACTION_BACK),10);h.postDelayed(()->performGlobalAction(GLOBAL_ACTION_HOME),40);}
 private void show(){if(wm==null||overlay!=null)return;LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setPadding(dp(28),dp(28),dp(28),dp(28));r.setBackground(grad(new int[]{Color.rgb(7,29,64),Color.rgb(34,112,188),Color.rgb(61,46,130)},0));r.setClickable(true);TextView i=lab("🛡",72,true);r.addView(i,new LinearLayout.LayoutParams(-1,dp(120)));TextView t=lab("הפעולה חסומה",30,true);r.addView(t,new LinearLayout.LayoutParams(-1,dp(60)));TextView m=lab("מכשיר זה מוגן על ידי Safe Steps",18,false);r.addView(m,new LinearLayout.LayoutParams(-1,dp(55)));TextView w=lab("המסך נסגר. יש להמתין שתי שניות…",15,false);r.addView(w,new LinearLayout.LayoutParams(-1,dp(55)));Button b=new Button(this);b.setText("חזור");b.setTextSize(17);b.setAllCaps(false);b.setEnabled(false);b.setOnClickListener(v->{performGlobalAction(GLOBAL_ACTION_HOME);remove();});r.addView(b,new LinearLayout.LayoutParams(-1,dp(58)));WindowManager.LayoutParams lp=new WindowManager.LayoutParams(-1,-1,WindowManager.LayoutParams.TYPE_ACCESSIBILITY_OVERLAY,WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN|WindowManager.LayoutParams.FLAG_FULLSCREEN,PixelFormat.TRANSLUCENT);try{wm.addView(r,lp);overlay=r;}catch(Exception ignored){}h.postDelayed(()->{if(b.getParent()!=null)b.setEnabled(true);if(w.getParent()!=null)w.setText("המסך נסגר. לחצו על חזור כדי לצאת.");},2000);}
 private TextView lab(String s,float z,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.WHITE);t.setGravity(17);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private GradientDrawable grad(int[] c,float r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,c);g.setCornerRadius(r);return g;}private int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private void remove(){if(overlay!=null){try{wm.removeView(overlay);}catch(Exception ignored){}}overlay=null;blocking=false;}
 public void onInterrupt(){remove();}public boolean onUnbind(Intent i){remove();return super.onUnbind(i);}
}
