package com.example.safesteps;
import android.app.*;import android.app.admin.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.provider.Settings;import android.text.InputType;import android.view.*;import android.widget.*;
public class MainActivity extends Activity {
 public static final String PREFS="safe_steps",PASSWORD="admin_password",TYPE="password_type",ENABLED="protection_enabled",PIN="pin",PATTERN="pattern";
 private boolean authed=false, settingsLaunch=false; private LinearLayout body; private TextView status;
 protected void onCreate(Bundle b){super.onCreate(b);init();authenticate();}
 private void init(){android.content.SharedPreferences p=getSharedPreferences(PREFS,0);if(!p.contains(PASSWORD))p.edit().putString(PASSWORD,"1234").putString(TYPE,PIN).putBoolean(ENABLED,false).apply();}
 protected void onResume(){super.onResume();if(settingsLaunch){settingsLaunch=false;return;}if(authed)showManager();}
 protected void onStop(){super.onStop();}
 private void authenticate(){authed=false; if(PATTERN.equals(getSharedPreferences(PREFS,0).getString(TYPE,PIN)))patternAuth();else pinAuth();}
 private LinearLayout root(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setPadding(dp(28),dp(25),dp(28),dp(30));r.setBackground(grad(new int[]{Color.rgb(7,29,64),Color.rgb(34,112,188),Color.rgb(61,46,130)},0));TextView i=txt("🛡",70,Color.WHITE,true);i.setGravity(17);r.addView(i,new LinearLayout.LayoutParams(-1,dp(100)));TextView t=txt("אימות מנהל",30,Color.WHITE,true);t.setGravity(17);r.addView(t,new LinearLayout.LayoutParams(-1,dp(55)));TextView s=txt("רק מנהל מורשה יכול להיכנס",16,Color.WHITE,false);s.setGravity(17);r.addView(s,new LinearLayout.LayoutParams(-1,dp(45)));return r;}
 private void pinAuth(){LinearLayout r=root();EditText e=new EditText(this);e.setHint("סיסמת מנהל");e.setTextColor(Color.WHITE);e.setHintTextColor(Color.LTGRAY);e.setTextSize(21);e.setGravity(17);e.setInputType(2|16);r.addView(e,new LinearLayout.LayoutParams(-1,dp(65)));Button b=btn("אימות");r.addView(b,new LinearLayout.LayoutParams(-1,dp(58)));b.setOnClickListener(v->{if(getSharedPreferences(PREFS,0).getString(PASSWORD,"1234").equals(e.getText().toString()))open();else e.setError("סיסמה שגויה");});setContentView(r);e.requestFocus();getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_VISIBLE);}
 private void patternAuth(){LinearLayout r=root();PatternLockView p=new PatternLockView(this);r.addView(p,new LinearLayout.LayoutParams(dp(300),dp(300)));Button b=btn("אימות");r.addView(b,new LinearLayout.LayoutParams(-1,dp(58)));b.setOnClickListener(v->{if(getSharedPreferences(PREFS,0).getString(PASSWORD,"").equals(p.getPattern()))open();else{Toast.makeText(this,"תבנית שגויה",Toast.LENGTH_SHORT).show();p.clearPattern();}});setContentView(r);}
 private void open(){authed=true;showManager();}
 private void showManager(){ScrollView sc=new ScrollView(this);sc.setBackgroundColor(Color.rgb(245,248,252));body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(18),dp(20),dp(28));sc.addView(body);TextView title=txt("Safe Steps",32,Color.rgb(20,43,76),true);title.setGravity(17);body.addView(title,new LinearLayout.LayoutParams(-1,dp(58)));TextView sub=txt("צעדים בטוחים בשבילך",17,Color.rgb(91,105,126),false);sub.setGravity(17);body.addView(sub,new LinearLayout.LayoutParams(-1,dp(38)));
 LinearLayout card=card();status=txt("",21,Color.rgb(20,43,76),true);card.addView(status,new LinearLayout.LayoutParams(-1,dp(48)));TextView typ=txt(PATTERN.equals(getSharedPreferences(PREFS,0).getString(TYPE,PIN))?"סוג סיסמה: קווים":"סוג סיסמה: מספרית",16,Color.rgb(91,105,126),false);card.addView(typ,new LinearLayout.LayoutParams(-1,dp(38)));Button toggle=btn("שינוי מצב ההגנה");card.addView(toggle,new LinearLayout.LayoutParams(-1,dp(54)));toggle.setOnClickListener(v->credential("שינוי מצב ההגנה",()->{boolean e=getSharedPreferences(PREFS,0).getBoolean(ENABLED,false);getSharedPreferences(PREFS,0).edit().putBoolean(ENABLED,!e).apply();refresh();}));body.addView(card,lp());
 LinearLayout actions=card();Button adm=btn("מנהל מכשיר");actions.addView(adm,new LinearLayout.LayoutParams(-1,dp(54)));adm.setOnClickListener(v->credential("מנהל מכשיר",this::admin));Button acc=btn("שירות ההגנה");actions.addView(acc,new LinearLayout.LayoutParams(-1,dp(54)));acc.setOnClickListener(v->{settingsLaunch=true;try{startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));}catch(Exception ignored){}});body.addView(actions,lp());
 TextView hint=txt("⋮  אפשרויות נוספות",17,Color.rgb(70,92,119),true);hint.setPadding(0,dp(10),0,dp(4));hint.setOnClickListener(v->menu(hint));body.addView(hint,new LinearLayout.LayoutParams(-1,dp(48)));refresh();setContentView(sc);}
 private void menu(View anchor){PopupMenu m=new PopupMenu(this,anchor);m.getMenu().add("שינוי סיסמת מנהל");m.getMenu().add("אודות");m.setOnMenuItemClickListener(i->{if(i.getTitle().toString().startsWith("שינוי"))credential("אימות מנהל",this::chooseType);else about();return true;});m.show();}
 private void refresh(){if(status==null)return;boolean e=getSharedPreferences(PREFS,0).getBoolean(ENABLED,false);status.setText(e?"● ההגנה פעילה":"● ההגנה כבויה");status.setTextColor(e?Color.rgb(13,151,91):Color.rgb(211,75,65));}
 private void credential(String title,Runnable ok){if(PATTERN.equals(getSharedPreferences(PREFS,0).getString(TYPE,PIN))){PatternLockView p=new PatternLockView(this);AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setMessage("ציירו את התבנית").setView(p).setNegativeButton("ביטול",null).setPositiveButton("אישור",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{if(getSharedPreferences(PREFS,0).getString(PASSWORD,"").equals(p.getPattern())){d.dismiss();ok.run();}else Toast.makeText(this,"אימות נכשל",Toast.LENGTH_SHORT).show();}));d.show();}else{EditText e=new EditText(this);e.setInputType(2|16);AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setMessage("הזינו את סיסמת המנהל").setView(e).setNegativeButton("ביטול",null).setPositiveButton("אישור",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{if(getSharedPreferences(PREFS,0).getString(PASSWORD,"1234").equals(e.getText().toString())){d.dismiss();ok.run();}else e.setError("אימות נכשל");}));d.show();}}
 private void chooseType(){RadioGroup g=new RadioGroup(this);RadioButton p=new RadioButton(this);p.setText("סיסמה מספרית");RadioButton q=new RadioButton(this);q.setText("סיסמת קווים");p.setTextSize(18);q.setTextSize(18);g.addView(p);g.addView(q);p.setChecked(true);AlertDialog d=new AlertDialog.Builder(this).setTitle("בחירת סוג סיסמה").setMessage("בחרו את סוג האימות החדש").setView(g).setNegativeButton("ביטול",null).setPositiveButton("המשך",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{d.dismiss();if(q.isChecked())newPattern();else newPin();}));d.show();}
 private void newPin(){EditText a=new EditText(this),b=new EditText(this);a.setHint("סיסמה חדשה");b.setHint("הקלדה חוזרת");a.setInputType(2);b.setInputType(2);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.addView(a);l.addView(b);AlertDialog d=new AlertDialog.Builder(this).setTitle("סיסמה מספרית חדשה").setView(l).setNegativeButton("ביטול",null).setPositiveButton("שמירה",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String x=a.getText().toString(),y=b.getText().toString();if(x.length()<4){a.setError("לפחות 4 ספרות");return;}if(!x.equals(y)){b.setError("לא זהה");return;}getSharedPreferences(PREFS,0).edit().putString(PASSWORD,x).putString(TYPE,PIN).apply();d.dismiss();Toast.makeText(this,"הסיסמה עודכנה",Toast.LENGTH_SHORT).show();}));d.show();}
 private void newPattern(){patternStep("ציירו סיסמה חדשה",x->patternStep("ציירו שוב לאימות",y->{if(!x.equals(y)){Toast.makeText(this,"התבניות אינן זהות",Toast.LENGTH_LONG).show();newPattern();return;}getSharedPreferences(PREFS,0).edit().putString(PASSWORD,x).putString(TYPE,PATTERN).apply();Toast.makeText(this,"הסיסמה עודכנה",Toast.LENGTH_SHORT).show();}));}
 interface Done{void go(String s);}private void patternStep(String title,Done done){PatternLockView p=new PatternLockView(this);AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setMessage("יש לבחור לפחות 4 נקודות").setView(p).setNegativeButton("ביטול",null).setPositiveButton("המשך",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{if(p.getPattern().length()<4){Toast.makeText(this,"לפחות 4 נקודות",Toast.LENGTH_SHORT).show();return;}d.dismiss();done.go(p.getPattern());}));d.show();}
 private void admin(){DevicePolicyManager d=(DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE);ComponentName c=new ComponentName(this,SafeStepsDeviceAdminReceiver.class);if(d.isAdminActive(c)){new AlertDialog.Builder(this).setTitle("מנהל מכשיר פעיל").setMessage("Safe Steps כבר מוגדרת כמנהלת מכשיר. כדי לבטל אותה, יש לאמת את המנהל ולאחר מכן לבטל את ההרשאה.").setNegativeButton("סגירה",null).setPositiveButton("ביטול הרשאה",(x,w)->credential("ביטול מנהל מכשיר",()->{d.removeActiveAdmin(c);Toast.makeText(this,"הרשאת מנהל המכשיר בוטלה",Toast.LENGTH_SHORT).show();})).show();return;}Intent i=new Intent(DevicePolicyManager.ACTION_ADD_DEVICE_ADMIN);i.putExtra(DevicePolicyManager.EXTRA_DEVICE_ADMIN,c);i.putExtra(DevicePolicyManager.EXTRA_ADD_EXPLANATION,"מנהל המכשיר מסייע למנוע הסרה רגילה של Safe Steps עד לביטול ההרשאה.");startActivity(i);}
 private void about(){new AlertDialog.Builder(this).setTitle("אודות Safe Steps").setMessage("© כל הזכויות שמורות לישראל מויאל.\n\nליצירת קשר פנו במייל:\ninm758595@gmail.com").setPositiveButton("סגירה",null).show();}
 private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(16),dp(18),dp(16));c.setBackground(grad(new int[]{Color.WHITE,Color.rgb(247,250,255)},dp(20)));return c;}private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(16);b.setAllCaps(false);return b;}private TextView txt(String s,float z,int col,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(col);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(15);return p;}private GradientDrawable grad(int[] c,float r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,c);g.setCornerRadius(r);return g;}private int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
}
