package com.example.safesteps;
import android.content.Context;import android.graphics.*;import android.util.AttributeSet;import android.view.MotionEvent;import android.view.View;import java.util.ArrayList;import java.util.List;
public class PatternLockView extends View {
 private final Paint dot=new Paint(1),sel=new Paint(1),line=new Paint(1); private final List<Integer> pts=new ArrayList<>(); private final float[] x=new float[9],y=new float[9]; private float r,cx,cy; private boolean draw;
 public PatternLockView(Context c){super(c);init();} public PatternLockView(Context c,AttributeSet a){super(c,a);init();} public PatternLockView(Context c,AttributeSet a,int s){super(c,a,s);init();}
 private void init(){dot.setColor(Color.rgb(211,222,235));sel.setColor(Color.rgb(40,125,225));line.setColor(Color.rgb(40,125,225));line.setStyle(Paint.Style.STROKE);line.setStrokeWidth(9);line.setStrokeCap(Paint.Cap.ROUND);line.setStrokeJoin(Paint.Join.ROUND);setBackgroundColor(Color.WHITE);}
 protected void onDraw(Canvas c){super.onDraw(c);float size=Math.min(getWidth(),getHeight()),l=(getWidth()-size)/2f,t=(getHeight()-size)/2f,cell=size/3f;r=cell*.15f;for(int row=0;row<3;row++)for(int col=0;col<3;col++){int i=row*3+col;x[i]=l+cell*col+cell/2;y[i]=t+cell*row+cell/2;}if(!pts.isEmpty()){Path p=new Path();p.moveTo(x[pts.get(0)],y[pts.get(0)]);for(int i=1;i<pts.size();i++)p.lineTo(x[pts.get(i)],y[pts.get(i)]);if(draw)p.lineTo(cx,cy);c.drawPath(p,line);}for(int i=0;i<9;i++){if(pts.contains(i)){c.drawCircle(x[i],y[i],r*1.45f,sel);dot.setColor(Color.WHITE);c.drawCircle(x[i],y[i],r*.42f,dot);dot.setColor(Color.rgb(211,222,235));}else c.drawCircle(x[i],y[i],r,dot);}}
 public boolean onTouchEvent(MotionEvent e){switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:clearPattern();draw=true;cx=e.getX();cy=e.getY();add(cx,cy);invalidate();return true;case MotionEvent.ACTION_MOVE:cx=e.getX();cy=e.getY();add(cx,cy);invalidate();return true;case MotionEvent.ACTION_UP:case MotionEvent.ACTION_CANCEL:cx=e.getX();cy=e.getY();add(cx,cy);draw=false;invalidate();return true;}return true;}
 private void add(float px,float py){for(int i=0;i<9;i++){float dx=px-x[i],dy=py-y[i];if(Math.sqrt(dx*dx+dy*dy)<=r*2.5&&!pts.contains(i)){pts.add(i);return;}}}
 public String getPattern(){StringBuilder b=new StringBuilder();for(Integer i:pts)b.append(i+1);return b.toString();} public void clearPattern(){pts.clear();draw=false;cx=cy=0;invalidate();}
}
